/**
 * Test fixtures.
 *
 * Everything here is built in memory at test time, with one deliberate
 * exception: the encrypted PDFs. pdf-lib (and the @cantoo/pdf-lib fork we
 * decrypt with) can read encryption but not write it, so those three cannot be
 * produced from inside a test run. They are generated by
 * scripts/generate-encrypted-fixtures.py and committed.
 *
 * Multi-page fixtures give every page a distinct size so a test can assert
 * *which* pages survived an operation, not merely how many. Asserting page
 * counts alone would pass for a split that returned the wrong pages.
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { PDFDocument } from "@cantoo/pdf-lib";

const FIXTURE_DIR = join(dirname(fileURLToPath(import.meta.url)), "fixtures");

/** Password on the committed encrypted fixtures. Mirrors the generator script. */
export const FIXTURE_PASSWORD = "correct-horse";

/** Page sizes used by makePdf and by the committed encrypted fixtures. */
export const pageSizeFor = (index: number): [number, number] => {
  const side = 200 + index * 100;
  return [side, side];
};

/** Identify a page by its size, so tests can assert page *identity*. */
export const pageIndexOf = (width: number): number => Math.round((width - 200) / 100);

/** Build an unencrypted PDF whose pages are individually identifiable. */
export async function makePdfBytes(pageCount: number): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  for (let i = 0; i < pageCount; i++) doc.addPage(pageSizeFor(i));
  return doc.save();
}

export async function makePdfFile(pageCount: number, name = "sample.pdf"): Promise<File> {
  const bytes = await makePdfBytes(pageCount);
  return new File([bytes], name, { type: "application/pdf" });
}

/** Read back the ordered page sizes of a produced PDF. */
export async function pageWidthsOf(source: Blob | Uint8Array): Promise<number[]> {
  const bytes = source instanceof Uint8Array ? source : new Uint8Array(await source.arrayBuffer());
  const doc = await PDFDocument.load(bytes);
  return doc.getPages().map((p) => Math.round(p.getWidth()));
}

/** The page indices, in order, that a produced PDF actually contains. */
export async function pageIndicesOf(source: Blob | Uint8Array): Promise<number[]> {
  return (await pageWidthsOf(source)).map(pageIndexOf);
}

/** Bytes that are definitively not a PDF — for error-path tests. */
export function makeCorruptPdfFile(name = "broken.pdf"): File {
  return new File([new Uint8Array([0x00, 0x01, 0x02, 0x03, 0x04])], name, {
    type: "application/pdf",
  });
}

// ---------------------------------------------------------------------------
// Encrypted fixtures (committed; see the module docstring)
// ---------------------------------------------------------------------------

export type EncryptedFixture =
  | "encrypted-rc4-128.pdf"
  | "encrypted-aes-256.pdf"
  | "encrypted-empty-password.pdf";

export function encryptedPdfFile(which: EncryptedFixture): File {
  const bytes = new Uint8Array(readFileSync(join(FIXTURE_DIR, which)));
  return new File([bytes], which, { type: "application/pdf" });
}

// ---------------------------------------------------------------------------
// Images
// ---------------------------------------------------------------------------

const PNG_1X1 =
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==";

const JPEG_1X1 =
  "/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/wAALCAABAAEBAREA/8QAFAABAAAAAAAAAAAAAAAAAAAACf/EABQQAQAAAAAAAAAAAAAAAAAAAAD/2gAIAQEAAD8AKp//2Q==";

const bytesFromBase64 = (b64: string): Uint8Array =>
  Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));

/**
 * `type` is settable because browsers hand back an empty MIME type for some
 * pickers and drag-drop sources — the case the audit's P1-15 covers, where a
 * valid image is rejected as "unsupported".
 */
export function pngFile(name = "image.png", type: string = "image/png"): File {
  return new File([bytesFromBase64(PNG_1X1)], name, { type });
}

export function jpegFile(name = "image.jpg", type: string = "image/jpeg"): File {
  return new File([bytesFromBase64(JPEG_1X1)], name, { type });
}

// ---------------------------------------------------------------------------
// DOCX
// ---------------------------------------------------------------------------

const MINIMAL_DOCX =
  "UEsDBBQAAAAIAIY1C13JTxqw6wAAAK4BAAATAAAAW0NvbnRlbnRfVHlwZXNdLnhtbH1QvU7DMBDeeQrLK4odGBBCSTrwMwJDeYCTfUks7LPlc0v79jht6YAK4933q69b7YIXW8zsIvXyRrVSIJloHU29/Fi/NPdScAGy4CNhL/fIcjVcdet9QhZVTNzLuZT0oDWbGQOwigmpImPMAUo986QTmE+YUN+27Z02kQpSacriIYfuCUfY+CKed/V9LJLRsxSPR+KS1UtIyTsDpeJ6S/ZXSnNKUFV54PDsEl9XgtQXExbk74CT7q0uk51F8Q65vEKoLP0Vs9U2mk2oSvW/zYWecRydwbN+cUs5GmSukwevzkgARz/99WHu4RtQSwMEFAAAAAgAhjULXbmBRHGwAAAAKgEAAAsAAABfcmVscy8ucmVsc43POw7CMAwG4J1TRN5pWgaEUJMuCKkrKgeIEjeNaB5KwqO3JwMDIAZG278/y233sDO5YUzGOwZNVQNBJ70yTjM4D8f1DkjKwikxe4cMFkzQ8VV7wlnkspMmExIpiEsMppzDntIkJ7QiVT6gK5PRRytyKaOmQciL0Eg3db2l8d0A/mGSXjGIvWqADEvAf2w/jkbiwcurRZd/nPhKFFlEjZnB3UdF1atdFRYob+nHi/wJUEsDBBQAAAAIAIY1C13UJZMPzAAAADwBAAARAAAAd29yZC9kb2N1bWVudC54bWxtj89qwzAMxu97CqP74nSHUkLs3kqPg7UPoMVaEvA/ZLdp3r5OunUwdvmE0E/fJ7X7m7PiSpzG4BVsqhoE+S6Y0fcKzqfD6w5EyugN2uBJwUwJ9vqlnRoTuosjn0Vx8KmZFAw5x0bK1A3kMFUhki+zr8AOc2m5l1NgEzl0lFIJcFa+1fVWOhw96GL5Gcy81LjKO6/lI8+WxNRc0So4Ei6nbUDqVj6ZVbI+jLd8YRLf0ALkFeMH/LT+wy+xIiJjzxiH6p89+XOb/P1b3wFQSwECFAMUAAAACACGNQtdyU8asOsAAACuAQAAEwAAAAAAAAAAAAAAgAEAAAAAW0NvbnRlbnRfVHlwZXNdLnhtbFBLAQIUAxQAAAAIAIY1C125gURxsAAAACoBAAALAAAAAAAAAAAAAACAARwBAABfcmVscy8ucmVsc1BLAQIUAxQAAAAIAIY1C13UJZMPzAAAADwBAAARAAAAAAAAAAAAAACAAfUBAAB3b3JkL2RvY3VtZW50LnhtbFBLBQYAAAAAAwADALkAAADwAgAAAAA=";

/** Minimal valid .docx: one Heading 1 and one body paragraph. */
export function docxFile(name = "sample.docx"): File {
  return new File([bytesFromBase64(MINIMAL_DOCX)], name, {
    type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  });
}
